### ISSUE TITLE
Use-Regex example # 1 not working

### ISSUE THREAD

**Issue by ptmorris1** [StartAutomating/Irregular#161]
I am unable to pipe anything into Use-Regex.  Even testing with Example # 1 in help file does not work for me.

**To Reproduce**
"abc" | Use-RegEx -Pattern '.'

**Expected behavior**
Not sure what is to be expected but assume no error.  Trying to learn and understand this cool module.

**Actual behavior**
Error I get:
Use-RegEx: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.

**Additional context**

**Comment by StartAutomating** [comment]
@ptmorris1 thanks for pointing this out.

It's a relic of old pipelining behavior of Use-Regex.

This will work:

~~~PowerShell
Use-RegEx -Pattern '.' -Text "abc"
~~~

and the example will be updated in the next release.

**Comment by StartAutomating** [comment]
@ptmorris1  Fixed!
