### ISSUE TITLE
Improve readability on the console when using `-Extract` to create  PSCustomObjects

### ISSUE THREAD

**Issue by ninmonkey** [StartAutomating/Irregular#35]
## Creating PSCO from `-Extract` is hard to read on the Commandline

The default output is hard to read on the command line, unless you filter properties.

## Wanted Behavior

Output where named capture groups become object properties, excluding `0` and `Match`

Example using `-match`
```powershell
$regex = @'
(?x)
# parse output from: "netstat -a -n -o
^\s+
(?<Protocol>\S+)
\s+
(?<LocalAddress>\S+)
\s+
(?<ForeignAddress>\S+)
\s+
(?<State>\S{0,})?
\s+
(?<Pid>\S+)$
'@

netstat -a -n -o | %{                                              
    if($_ -match $regex) {                                         
      $matches.remove(0)                                           
      [pscustomobject]$Matches                                     
    }                                                              
} | select -Last 2 -ov 'last'                                      
| ft                                                               
                                                                   
$last | fl                                                                                                 
```

![image](https://user-images.githubusercontent.com/3892031/113779015-b4881000-96f2-11eb-8005-1004ad6ee2fc.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/3892031/113778572-30ce2380-96f2-11eb-9417-4bedd0c08094.png)

```powershell
netstat -a -n -o 
| Use-RegEx -Extract -Pattern $regex -Match { $_ } -ea SilentlyContinue
| select -Last 2 -ov last
|Ft

$last | fl
````

## Change

Removing or hiding the the `[Match]` and `0` properties by default when using `-Extract`

```powershell
netstat -a -n -o 
| Use-RegEx -Extract -Pattern $regex -Match { $_ } -ea SilentlyContinue
| select -ExcludeProperty 'match', '0'
| select -Last 2 -ov last
| ft

$last | fl
```
![image](https://user-images.githubusercontent.com/3892031/113779531-7c350180-96f3-11eb-97d5-38d225c27626.png)

**Comment by StartAutomating** [comment]
Issue fixed in .0.5.6

Closing
