### ISSUE TITLE
IPv4Address RegEx matches invalid IPs

### ISSUE THREAD

**Issue by clsmith70** [StartAutomating/Irregular#38]
When matching IPv4 groups of numbers, invalid IPs are matched as well as valid IPs

$ipRegex = Write-RegEx -Pattern ?<IPv4Address>
$ipRegex.Matches('192.168.86.153,256.199.381.31,10.0.0.1')

StartIndex EndIndex Value
---------- -------- -----
0          14       192.168.86.153
15         29       256.199.381.31      <-- should not match
30         38       10.0.0.1

**Comment by StartAutomating** [comment]
@clsmith70 Thanks for the bug! 

To be clear on the original intent here:  I'm not trying to make matches perfect, just "close enough to try to cast".  So all else being equal, it doesn't bother me a lot to have a regular expression that's easier to understand/faster (but sometimes wrong).

That stated.

It's a common enough scenario to want to match a range of numbers up to a given point, and it's a "well-known", if tedious, RegEx trick (see [this tutorial on Numeric Ranges in RegEx](https://www.regular-expressions.info/numericranges.html) ).

So I decided to make this RegEx more accurate and add a supporting parameter to Write-RegEx:  -DigitMax

I then changed the source file / regex for ?<IPv4Address> to make something that should only match numbers between 0-255.

The PR is in now and it will be in the next full build.

Please let me know if it works as expected.

**Comment by StartAutomating** [comment]
@clsmith70 Fix integrated into .0.5.7

Closing the issue
